### PR TITLE
add polish

### PR DESCRIPTION
**Pull request by vincentkerdraon**

### CODE REVIEW

**Comment by vincentkerdraon** [comment]
@aBOOminacja 
 A big thanks for this new translation!
 Is your contribution name ok on https://accounts.klei.com/community-translations ?
 And can you quickly check if everything feels ok in the translated pages.

**Comment by aBOOminacja** [comment]
Oh you can change contribution name to abominacja (H☮PE) if it is possible
or just abominacja (HOPE) but yeah and i looked at the website and
everything feels good except for word wydaj (redeem) i think the word
"rozdaj" will be better because it in my opinion will work better for klei
points like u know u will give away points for some items p.s thank u so
much for adding my translation im so happy.

pon., 26 lip 2021 o 19:18 Vincent KERDRAON ***@***.***>
napisał(a):

**Comment by vincentkerdraon** [comment]
@aBOOminacja I get to thank you.

I am deploying your translator name in https://accounts.klei.com/community-translations .
It should be good in a few minutes.

I will let you create a new PR (https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) with any changes you see fit.
I prefer to avoid doing corrections to your text because I don't talk Polish and I could make a mistake.

Have a good day.

**Comment by aBOOminacja** [comment]
Thanks :D also Can you explain to me what the percentages mean in the translation if it says polish 88%, it means that I can translate something else that was not on the list?
obraz_2021-07-27_010031
I apologize in advance for my lack of knowledge, I am working on such things for the first time

**Comment by vincentkerdraon** [comment]
@aBOOminacja 
I fixed the percentage. Polish is at 100% !!!!
(This is a manual operation, and was missing).

**Pull request merged**
