### PR TITLE
Ukrainian

### PR DESCRIPTION
**Pull request by SkyFly97**

### CODE REVIEW

**Comment by SkyFly97** [comment]
> Looking up the ISO 639-1 codes, it LOOKS like Ukranian should be uk instead of ua. That said, I'm not a Ukrainian expert. Can you please either confirm it should be ua, or change it to uk? Thank you so much for your translation!

My bad. It should be uk.

**Comment by mikebell-org** [comment]
No worries! Let me know when the pull request is updated to use uk and we'll get it merged. Thank you so much for the translation!

**Comment by mikebell-org** [comment]
Excellent! Today a holiday here in Canada, but tomorrow @cixtor will get that deployed to the production website.
Thanks for helping Ukrainian Klei fans!

**Comment by SkyFly97** [comment]
Thanks, have a good holiday!

**Pull request merged**
