### PR TITLE
ru

### PR DESCRIPTION
**Pull request by UnitedMel**
[ru.txt](https://github.com/kleientertainment/KleiAccountsLocale/files/3557749/ru.txt)

### CODE REVIEW

**Comment by cixtor** [comment]
Hello @UnitedMel, thank you for your contribution.

Unfortunately, the pull-request you created doesn’t contain the translation in a commit. I notice that you decided to attach a file instead, but this makes it impossible for me to merge your changes into the Git repository.

But don’t worry, I went ahead and added the “ru.txt” file myself with your translation and a few corrections. The language is now available in the website right now, and your name has been added to the “Community Translations” page as you can see here — https://accounts.klei.com/community-translations

For future contributions, please follow these steps:

1. Open any of the localization files using your favorite text editor
2. Translate or make corrections as you would do in any document
3. Save your changes and then execute these commands:
4. Use `git add -A` to stage your changes
5. Use `git commit -m "FOO"` to commit your changes. Replace “Foo” with a description of what changes you are applying, it can be a simple message like “Adding Spanish translation” or “Fixing grammar mistakes in the Spanish localization file”. You can see more [examples here](https://github.com/kleientertainment/KleiAccountsLocale/commits/master)
6. Use `git push` to upload your commits to GitHub
7. [Create the pull-request as instructed in this page](https://help.github.com/en/articles/creating-a-pull-request)
7. Click the tab named **“Files changed”** at the top of the pull-request to make sure that your changes _(usually highlighted in green)_ are correct. If you are missing changes, go back to step 4 and follow along

Thank you very much.

**Comment by mikebell-org** [comment]
Thanks so much for your Russian translation @UnitedMel ! We really appreciate you going to all the trouble to make our first fan translation on the accounts site! I'm sure all the Russian-speaking Klei fans appreciate your hard work as well!

**Comment by UnitedMel** [comment]
Thank you for your kind words. I am very happy to help you with the translation of the site!

P.S. For some reason, the rewards section is still displayed in English, although I translated all the “names” in the text file. ¯\_(⊙_ʖ⊙)_/¯

**Comment by mikebell-org** [comment]
@UnitedMel can you please chime in on https://github.com/kleientertainment/KleiAccountsLocale/pull/4 ?

**Pull request merged**
