### PR TITLE
Some uk and ru fixes

### PR DESCRIPTION
**Pull request by SkyFly97**

### CODE REVIEW

**Comment by mikebell-org** [comment]
@UnitedMel does this look good to you? I'd prefer a consensus-driven approach obviously.

**Comment by SkyFly97** [comment]
There's just “markeNting” instead of “marketing,” that's all, nothing serious.

**Comment by UnitedMel** [comment]
Yep

**Comment by mikebell-org** [comment]
Thanks to both of you! We'll get this deployed shortly.

**Pull request merged**
