### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by xiaopangju**

### CODE REVIEW

**Comment by klei-peggy** [comment]
Sorry for the very late review, can you please change the following strings:
"Klei Support Issued Currency": 科雷客服发放的游戏货币
"Klei Support Issued Item": 科雷客服发放的游戏物品

Thank you!

**Review by klei-peggy — CHANGES_REQUESTED** [review]

**Comment by xiaopangju** [comment]
@klei-peggy Thank you for your reviewing. I think translate "Klei Support" into "科雷支持" is correct. This is a common translation. Apple translate "Apple support" into "Apple 支持" and Microsoft translate "Microsoft support" into "Microsoft 支持", for example.
Reference:https://support.microsoft.com/
https://support.apple.com/zh-cn
图片
图片

**Comment by klei-peggy** [comment]
> @klei-peggy Thank you for your reviewing. I think translate "Klei Support" into "科雷支持" is correct. This is a common translation. Apple translate "Apple support" into "Apple 支持" and Microsoft translate "Microsoft support" into "Microsoft 支持", for example. Reference:https://support.microsoft.com/ https://support.apple.com/zh-cn 图片 图片

Yes, you're right, 科雷支持 is acceptable too!

**Comment by xiaopangju** [comment]
> > @klei-peggy Thank you for your reviewing. I think translate "Klei Support" into "科雷支持" is correct. This is a common translation. Apple translate "Apple support" into "Apple 支持" and Microsoft translate "Microsoft support" into "Microsoft 支持", for example. Reference:https://support.microsoft.com/ https://support.apple.com/zh-cn 图片 图片
> 
> Yes, you're right, 科雷支持 is acceptable too!

Can you approve this PR? Thanks!

**Comment by xiaopangju** [comment]
@klei-peggy By the way, Github says that "This branch has conflicts that must be resolved". What should I do?

**Comment by klei-peggy** [comment]
@xiaopangju There are still some changes that can be made. 
Klei支持颁发的货币 -> 科雷支持发放的游戏货币
Klei支持颁发的物品 -> 科雷支持发放的游戏物品

You can pull the latest version of of this file into your version and find the conflicts to fix them.

**Pull request closed without merging**
